### ISSUE TITLE
UMD?

### ISSUE THREAD

**Issue by chocolateboy** [privatenumber/repkg#6]
This looks really useful! A nice alternative to [packd](https://bundle.run/), which often seems to be down when I try to use it.

However, I almost overlooked it because it repeatedly mentions [AMD](https://sodocumentation.net/javascript/topic/4655/modularization-techniques#asynchronous-module-definition--amd-) bundles (i.e. asynchronous RequireJS bundles), so I assumed it was for some specific (legacy?) use case.

But looking at the generated output, it appears to be producing [UMD](https://sodocumentation.net/javascript/topic/4655/modularization-techniques#universal-module-definition--umd-) bundles (which work in Node.js, the browser *and* RequireJS), which are much more useful. Universal in fact!

Since AMD is just one of the 3 environments it supports, and probably the least used/useful these days, is there a reason the documentation refers to AMD bundles rather than UMD bundles?

**Comment by privatenumber** [comment]
Thanks for the feedback @chocolateboy !

The primary use-case for REPKG is to create web-distributions for packages that don't have one.

Of the three formats UMD supports (CommonJS, AMD, Global), AMD is the only useful format for the web because it's the only one that creates a "module" (encapsulated/non-polluting and enforces dependency resolution order). CommonJS can't be loaded without a transformer because modules are loaded asynchronously, and Globals can't really resolve dependencies or enforce dependency resolution order.

AMD is outdated but still useful. As an alternative, there's also SystemJS and ESM.

I chose UMD over SystemJS so that modules that don't have dependencies can still be loaded independently without a module-loader (eg. like RequireJS or SystemJS).

I made this service because I couldn't use ESM (the services I wanted to use this for supported some older browsers). If you want a modern format, ESM is natively supported by evergreen browsers and there's services like [jspm](https://jspm.org), PikaCDN/[Skypack](https://www.skypack.dev/) that re-bundle packages to ESM for you.

**Comment by chocolateboy** [comment]
> Of the three formats UMD supports (CommonJS, AMD, Global), AMD is the only useful format for the web because it's the only one that creates a "module" (encapsulated/non-polluting and enforces dependency resolution order). 

UMD has always worked fine for me on the web (and in other browser-like environments such as SpiderMonkey and QuickJS) without AMD/RequireJS, whether by assigning to `globalThis`/`window`, or by assigning to a dummy `exports`/`module.exports` global ([e.g.](https://github.com/chocolateboy/uncommonjs)), which is cleaner/safer than assigning to the global object.

As for the dependency resolution order: UMD bundles usually include the dependencies (or at least mine do), so it's all static/synchronous.

> I made this service because I couldn't use ESM (the services I wanted to use this for supported some older browsers).

Thanks for sharing the rationale. That makes sense. (My use case is mainly [userscripts](https://wiki.greasespot.net/Metadata_Block#.40require).)

I guess I'm just wondering if you might be burying the lede of a very useful service slightly since AMD is just one of the three formats, and IMO it gives the impression that the other two aren't supported. I assume most people who are using RequireJS are using a build/deployment toolchain, and so would be far less likely to use a service like this than those of us who consume (and publish) UMD bundles as a last resort when no better options are available.

> If you want a modern format, ESM is natively supported by evergreen browsers

No, I need an ancient format for broken environments :-) The appeal/USP of UMD is that you can just stick the links in a quick demo page/userscript etc. and it works when all else fails.

Closing this since your use case makes sense (of course), but I'll probably still [refer](https://github.com/chocolateboy/uncommonjs/tree/develop#see-also) to the service as a UMD bundler since that seems far more useful (to me) than the AMD support :-)
